s3 check

diff --git a/.github/workflows/manage-eks-cluster.yml b/.github/workflows/manage-eks-cluster.yml
--- a/.github/workflows/manage-eks-cluster.yml
+++ b/.github/workflows/manage-eks-cluster.yml
@@ -1,4 +1,4 @@
-name: Manage EKS Cluster
+name: Manage EKS Cluster and Check S3 Access
 
 on:
   workflow_dispatch:
@@ -14,20 +14,42 @@ on:
         required: true
 
 jobs:
+  check_s3_access:
+    runs-on: ubuntu-latest
+    outputs:
+      s3_check_success: ${{ steps.check_s3.outputs.success }}
+    steps:
+    - name: Set up AWS CLI
+      uses: aws-actions/configure-aws-credentials@v2
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ github.event.inputs.awsRegion }}
+
+    - name: Check S3 Access
+      id: check_s3
+      run: |
+        aws s3 ls
+        if [ $? -ne 0 ]; then
+          echo "S3 access check failed."
+          exit 1
+        else
+          echo "S3 access check passed."
+          echo "::set-output name=success::true"
+        fi
+
   apply_cluster:
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.action == 'apply' }}
+    needs: check_s3_access
+    if: needs.check_s3_access.outputs.s3_check_success == 'true' && ${{ github.event.inputs.action == 'apply' }}
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Setup Terraform
+    - name: Set up Terraform
       uses: hashicorp/setup-terraform@v1
-
-    - name: Set AWS Credentials
-      run: |
-        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
-        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+      with:
+        terraform_version: 1.3.9  # Adjust the Terraform version as needed
 
     - name: Terraform Init
       run: terraform init
@@ -47,24 +69,22 @@ jobs:
 
   destroy_cluster:
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.action == 'destroy' }}
+    needs: check_s3_access
+    if: needs.check_s3_access.outputs.s3_check_success == 'true' && ${{ github.event.inputs.action == 'destroy' }}
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Setup Terraform
+    - name: Set up Terraform
       uses: hashicorp/setup-terraform@v1
-
-    - name: Set AWS Credentials
-      run: |
-        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
-        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+      with:
+        terraform_version: 1.3.9  # Adjust the Terraform version as needed
 
     - name: Terraform Init
       run: terraform init
       working-directory: Terraform
 
-    - name: Terraform FMT
+    - name: Terraform Format
       run: terraform fmt
       working-directory: Terraform
 
